<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CanberKeytorc" name="ThirdTest" tests="1" failures="1" timestamp="7 Feb 2016 09:53:12 GMT" time="24.627" errors="0">
  <testcase name="test1" time="6.205" classname="com.bilyoner.Stack.AppTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.bilyoner.Stack.AppTest.test1(AppTest.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- ThirdTest -->
